#cloud-config
preserve_hostname: true
fqdn: ${fqdn}
hostname: ${hostname}

runcmd:
  - [ systemctl, stop, ufw]
  - [ systemctl, disable, ufw]

write_files:
  - path: /etc/consul.d/consul.hcl
    owner: consul:consul
    permissions: '0644'
    content: |
      datacenter = "${datacenter}"
      data_dir = "/opt/consul/"
      encrypt = "Luj2FZWwlt8475wD1WtwUQ=="
      retry_join = ["${consul_0}", "${consul_1}", "${consul_2}"]
      bind_addr = "{{ GetInterfaceIP `eth1` }}"

  - path: /etc/nomad.d/nomad.hcl
    owner: nomad:nomad
    permissions: '0644'
    content: |
      datacenter = "${datacenter}"
      data_dir  = "/mnt/nomad/data"
      bind_addr = "0.0.0.0"
      advertise {
        http = "{{ GetInterfaceIP `eth1` }}"
        rpc  = "{{ GetInterfaceIP `eth1` }}"
        serf = "{{ GetInterfaceIP `eth1` }}"
      }

      server {
        enabled          = true
        bootstrap_expect = 3
      }

      consul {
        address = "127.0.0.1:8500"
      }

      telemetry {
        collection_interval = "1s"
        disable_hostname = true
        prometheus_metrics = true
        publish_allocation_metrics = true
        publish_node_metrics = true
      }